name: 'd2m-pipeline'
description: 'A GitHub Action to trigger deployment pipeline on machine running self hosted d2m instance'
inputs:
  message:
    description: 'The message to log'
    default: 'Hello World'
    required: true
runs:
  using: 'node20'
  main: 'lib/index.js'
